name: Garuda_CI_CD
on:
  push:
    branches: [data_extractor, queue_worker, main]
  pull_request:
    branches: [data_extractor, queue_worker, main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "adopt"
    
    - name: Build and Install data_extractor with Maven
      working-directory: ./data_extractor
      run: |
        mvn test
        mvn clean
        mvn assembly:single
        mvn install
    
    # Clean and Build Queue Worker Module
    - name: Build queue_worker with Maven
      working-directory: ./queue_worker
      run: |
        mvn clean
        mvn compile assembly:single

    # Install and Test db_middleware module
    - uses: actions/checkout@v2
    - name: Use Node.js LTS Gallium
      uses: actions/setup-node@v2
      with:
        node-version: "lts/gallium"
        cache: "npm"
        cache-dependency-path: '**/package-lock.json'
    - name: Build db_middleware with npm
      working-directory: ./db_middleware
      run: |
        npm install
        npm test

    # Build Web-App module
    - uses: actions/checkout@v2
    - name: Use Node.js LTS Gallium
      uses: actions/setup-node@v2
      with:
        node-version: "lts/gallium"
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Build Web-App module
      working-directory: ./web_app
      run: |
        npm ci
        CI="" npm run build --if-present
    

    - name: executing remote ssh commands using key file
      uses: appleboy/ssh-action@master
      with:
        host: 149.165.154.67
        username: exouser
        key: ${{ secrets.JETSTREAM_PVT_KEY }}
        port: 22
        script: |
          cd ~/garuda/kubernetes
          sh kubernetes_down.sh
          cd ../..
          rm -rf garuda
          git clone https://github.com/airavata-courses/garuda.git
          cd garuda/kubernetes
          sh kubernetes_init.sh